// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RaoBlackwell
List RaoBlackwell(NumericMatrix beta_select, NumericMatrix se_select, NumericMatrix Rxy, NumericMatrix Rxysqrt, double eta, double cutoff, int B, bool onlyexposure, int n_threads);
RcppExport SEXP _RBCorrection_RaoBlackwell(SEXP beta_selectSEXP, SEXP se_selectSEXP, SEXP RxySEXP, SEXP RxysqrtSEXP, SEXP etaSEXP, SEXP cutoffSEXP, SEXP BSEXP, SEXP onlyexposureSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type beta_select(beta_selectSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type se_select(se_selectSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rxy(RxySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Rxysqrt(RxysqrtSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type onlyexposure(onlyexposureSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(RaoBlackwell(beta_select, se_select, Rxy, Rxysqrt, eta, cutoff, B, onlyexposure, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// grapple_stat_multi_cpp
Rcpp::List grapple_stat_multi_cpp(const arma::cube& RxyList, const arma::vec& theta, const arma::vec& e, int n_threads);
RcppExport SEXP _RBCorrection_grapple_stat_multi_cpp(SEXP RxyListSEXP, SEXP thetaSEXP, SEXP eSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type RxyList(RxyListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grapple_stat_multi_cpp(RxyList, theta, e, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// grapple_stat_uni_cpp
Rcpp::List grapple_stat_uni_cpp(const arma::cube& RxyList, double theta, const arma::vec& e, int n_threads);
RcppExport SEXP _RBCorrection_grapple_stat_uni_cpp(SEXP RxyListSEXP, SEXP thetaSEXP, SEXP eSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type RxyList(RxyListSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grapple_stat_uni_cpp(RxyList, theta, e, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// biasterm
arma::mat biasterm(const arma::cube& RxyList, const arma::uvec& indvalid, int n_threads);
RcppExport SEXP _RBCorrection_biasterm(SEXP RxyListSEXP, SEXP indvalidSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type RxyList(RxyListSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type indvalid(indvalidSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(biasterm(RxyList, indvalid, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// MRcML_bXest
arma::mat MRcML_bXest(const arma::cube& ThetaList, const arma::mat& bX, const arma::vec& e, const arma::vec& theta, int n_threads);
RcppExport SEXP _RBCorrection_MRcML_bXest(SEXP ThetaListSEXP, SEXP bXSEXP, SEXP eSEXP, SEXP thetaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type ThetaList(ThetaListSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bX(bXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(MRcML_bXest(ThetaList, bX, e, theta, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// MRcML_UV_bxest
arma::vec MRcML_UV_bxest(const arma::cube& ThetaList, const arma::vec& bx, const arma::vec& e, double theta, int n_threads);
RcppExport SEXP _RBCorrection_MRcML_UV_bxest(SEXP ThetaListSEXP, SEXP bxSEXP, SEXP eSEXP, SEXP thetaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type ThetaList(ThetaListSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bx(bxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(MRcML_UV_bxest(ThetaList, bx, e, theta, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RBCorrection_RaoBlackwell", (DL_FUNC) &_RBCorrection_RaoBlackwell, 9},
    {"_RBCorrection_grapple_stat_multi_cpp", (DL_FUNC) &_RBCorrection_grapple_stat_multi_cpp, 4},
    {"_RBCorrection_grapple_stat_uni_cpp", (DL_FUNC) &_RBCorrection_grapple_stat_uni_cpp, 4},
    {"_RBCorrection_biasterm", (DL_FUNC) &_RBCorrection_biasterm, 3},
    {"_RBCorrection_MRcML_bXest", (DL_FUNC) &_RBCorrection_MRcML_bXest, 5},
    {"_RBCorrection_MRcML_UV_bxest", (DL_FUNC) &_RBCorrection_MRcML_UV_bxest, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RBCorrection(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
