# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RaoBlackwellCorrect <- function(beta_select, se_select, Rxy, eta, cutoff, B, onlyexposure = TRUE, n_threads = 1L) {
    .Call(`_RBCorrection_RaoBlackwellCorrect`, beta_select, se_select, Rxy, eta, cutoff, B, onlyexposure, n_threads)
}

RaoBlackwellCorrect_UV <- function(gamma, sigma, cutoff, B, eta = 1.0, n_threads = 1L) {
    .Call(`_RBCorrection_RaoBlackwellCorrect_UV`, gamma, sigma, cutoff, B, eta, n_threads)
}

update_theta_e <- function(by, bx, byse, ThetaList, vartheta, indvalid, n_threads = 0L) {
    .Call(`_RBCorrection_update_theta_e`, by, bx, byse, ThetaList, vartheta, indvalid, n_threads)
}

