# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RaoBlackwell <- function(beta_select, se_select, Rxy, Rxysqrt, eta, cutoff, B, onlyexposure = TRUE, n_threads = 1L) {
    .Call(`_RBCorrection_RaoBlackwell`, beta_select, se_select, Rxy, Rxysqrt, eta, cutoff, B, onlyexposure, n_threads)
}

